# Generated by Django 3.2.8 on 2022-06-30 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userl', '0003_alter_assigmnet_roomcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sroominfo',
            name='roomimg',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
