# Generated by Django 3.2.8 on 2022-06-30 22:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20220630_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_info',
            name='phoneno',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='phoneno',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_info',
            name='phoneno',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 4, 23, 36, 184965)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 4, 23, 36, 184965)),
        ),
    ]
