# Generated by Django 3.2.8 on 2022-06-30 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20220701_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempotp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10, unique=True)),
                ('otp', models.CharField(default=None, max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 4, 49, 25, 499945)),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 4, 49, 25, 499945)),
        ),
    ]
