# Generated by Django 3.2.8 on 2022-06-30 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teachl', '0008_auto_20220606_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominfo',
            name='roomimg',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
